[green_agent]
agentbeats_id = "019bc25f-f5d9-7582-b51e-d5d3704cdf97"
env = { API_KEY = "${GITHUB_SECRET_NAME}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "role_1_name"
env = {}

[[participants]]
agentbeats_id = ""
name = "role_2_name"
env = {}

[config]
# Add your assessment config here
