[green_agent]
agentbeats_id = "019bc25f-f5d9-7582-b51e-d5d3704cdf97"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc282-671e-7731-9dd9-0d86d3d5a29e"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[config]
domain = "healthcare"
num_tasks = 50
mcp_server_url = "http://medagentbench.ddns.net:8002"
fhir_server_url = "http://medagentbench.ddns.net:8080/fhir"
