[green_agent]
agentbeats_id = "019bc49c-c267-7f42-bc7d-b9b3f318b932"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019bc282-671e-7731-9dd9-0d86d3d5a29e"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[config]
domain = "healthcare"
fhir_api_base = "http://medagentbench.ddns.net:8080/fhir/"
mcp_server_url = "http://medagentbench.ddns.net:8002"

#num_tasks = 11

task_ids = [
  "task1_1",
  "task2_1", 
  "task3_1", 
  "task4_1", 
  "task5_1",
  "task6_1",
  "task7_1",
  "task8_1", 
  "task9_1",
  "task10_1",
  "task11_1"
]

# Multi-Worker Parallel Execution Configuration.
# Number of agent worker processes to spawn for true parallelism.
num_workers=1